sources:
  inputLocation: "concepts/thesaurus.ttl"
  ignorePathsWith:
    - "old"
  outputLocation: "respec/rdf2respec"
  reSpecMapping:
    type: hierarchical
    prefixes:
      rdfs: "http://www.w3.org/2000/01/rdf-schema#"
      skos: "http://www.w3.org/2004/02/skos/core#"
      skosthes: "http://purl.org/iso25964/skos-thes#"
      dct: "http://purl.org/dc/terms/"
      skosapnl: "http://pldn.nl/nederlands-profiel-voor-stelselcatalogi/id/concept/"
      edit: "http://definities.geostandaarden.nl/def/editorial#"
    hierarchicalRelation: 
      direction: upward
      predicates:
        - skos:broader
    sectionTitlePredicate: skos:prefLabel
    attributeMapping:
      voorkeursterm: skos:prefLabel
      alternative label: skos:altLabel
      definitie: skos:definition
      label: rdfs:label
      bovenliggend begrip: skos:broader
      behoort tot: skos:inScheme
      bron: dct:source
      gerelateerd begrip: skos:related
      is specialisatie van: skosthes:broaderGeneric
      is onderdeel van: skosthes:broaderPartitive
      exemplaar van: skosthes:broaderInstantial
      is generalisatie van: skosthes:narrowerGeneric
      categorie van: skosthes:narrowerInstantial
      omvat: skosthes:narrowerPartitive
      overeenkomstig generieker: skos:broadMatch
      exact overeenkomstig: skos:exactMatch
      Overeenkomstig verwant: skos:relatedMatch
      vrijwel overeenkomstig: skos:closeMatch
      voorbeeld: skos:example
      zoekterm: skos:hiddenLabel
      historische notitie: skos:historyNote
      toelichting: skos:scopeNote
      redactionele opmerking: skos:editorialNote
      uitleg: rdfs:comment
      code: skos:notation
    issueMapping:
      issuePredicate: edit:issue
      issueIdPredicate: dct:identifier