name: Publish to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  rdf2respec-begrippenkader:
    name: rdf2respec-begrippenkader
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch rdf2rdf
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "architolk/rdf2rdf"
          tag: "v1.1.0"
          fileName: "rdf2rdf.jar"
      - name: generate markdown (0/2)
        run: touch respec/rdf2markdown/begrippenkader.xml
      - name: generate markdown (1/2)
        run: java -jar rdf2rdf.jar concepts/*.ttl respec/rdf2markdown/begrippenkader.xml
      - name: generate markdown (2/2)
        run: java -jar respec/rdf2markdown/jars/saxon9.jar -s:respec/rdf2markdown/begrippenkader.xml -xsl:respec/rdf2markdown/begkr2md.xsl -o:respec/rdf2markdown/begrippenkader.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2respec-begrippenkader_output
          path: respec/rdf2markdown/begrippenkader.*
  rdf2respec-profile:
    name: rdf2respec-profile
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: generate markdown (0/2)
        run: touch respec/rdf2markdown/profile.xml
      - name: generate markdown (1/2)
        run: java -jar respec/rdf2markdown/jars/rdf2rdf-0.0.1-SNAPSHOT-jar-with-dependencies.jar profiles/*.ttl respec/rdf2markdown/profile.xml
      - name: generate markdown (2/2)
        run: java -jar respec/rdf2markdown/jars/saxon9.jar -s:respec/rdf2markdown/profile.xml -xsl:respec/rdf2markdown/prof2md.xsl -o:respec/rdf2markdown/profile.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2respec-profile_output
          path: respec/rdf2markdown/profile.*

  main:
    needs: [rdf2respec-begrippenkader, rdf2respec-profile]
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download rdf2respec-begrippenkader output
        uses: actions/download-artifact@v3
        with:
          name: rdf2respec-begrippenkader_output
          path: respec/rdf2respec
      - name: Download rdf2respec-profile output
        uses: actions/download-artifact@v3
        with:
          name: rdf2respec-profile_output
          path: respec/rdf2respec
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages


