name: Publish to GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  rdf2respec-begrippenkader:
    name: rdf2respec-begrippenkader
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: generate
        run: java -jar respec/rdf2respec/rdf2respec-0.1.0-SNAPSHOT.jar
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2respec-begrippenkader_output
          path: respec/rdf2respec/*.md
  rdf2respec-profile:
    name: rdf2respec-profile
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: generate markdown (0/2)
        run: touch respec/rdf2respec/profile/profile.xml
      - name: generate markdown (1/2)
        run: java -jar respec/rdf2respec/profile/rdf2rdf-0.0.1-SNAPSHOT-jar-with-dependencies.jar profiles/*.ttl respec/rdf2respec/profile/profile.xml
      - name: generate markdown (2/2)
        run: java -jar respec/rdf2respec/profile/saxon9.jar -s:respec/rdf2respec/profile/profile.xml -xsl:respec/rdf2respec/profile/xml2md.xsl -o:respec/rdf2respec/profile/profile.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2respec-profile_output
          path: respec/rdf2respec/profile/profile.*

  main:
    needs: [rdf2respec-begrippenkader, rdf2respec-profile]
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download rdf2respec-begrippenkader output
        uses: actions/download-artifact@v3
        with:
          name: rdf2respec-begrippenkader_output
          path: respec/rdf2respec
      - name: Download rdf2respec-profile output
        uses: actions/download-artifact@v3
        with:
          name: rdf2respec-profile_output
          path: respec/rdf2respec
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages


